Add German Translation
CodingGarden/discord-welcome-code-of-conduct pull request #2
Opened 2019-12-06 16:27 UTC by spVierSechs

I'm not sure what happened with the last line of README here, but it should be the same despite GitHub's `diff` saying otherwise.

2019-12-06 22:09 UTC, snordmann requested changes
Hi @spVierSechs 👋, thanks for your translation 👍 

I looked over it and fixed some minor spelling or grammatical errors.
I think we might need to reword the section `**Achte auf deine Wortwahl.**`; Especially the first bullet point has some improvement potential. I currently have no idea how to write it more concisely and still be broad enough to cover everything.

Other than that: Looks good! Thank you again for your work 😊

2019-12-06 22:09 UTC, snordmann commented on README.md
> +React with an emoji to acknowledge that you have read this message and agree to follow the code of conduct! :point_down:
You added an extra new line at the end of the file.

2019-12-06 22:09 UTC, snordmann commented on README_GERMAN.md
> +>Hey! Wir brauchen deine Hilfe dabei, diese Nachricht in andere Sprachen zu übersetzen. Siehe [CONTRIBUTING](./CONTRIBUTING.md) für mehr details.
```suggestion
>Hey! Wir brauchen deine Hilfe dabei, diese Nachricht in andere Sprachen zu übersetzen. Siehe [CONTRIBUTING](./CONTRIBUTING.md) für mehr Details.
```

2019-12-06 22:09 UTC, snordmann commented on README_GERMAN.md
> +Bevor du zu den anderen Channels zugrif bekommst, musst du dich in #🗣introductions (mit wenigstens 40 Zeichen) vorstellen und zeigen, dass du den Verhaltenskodex weiter unten gelesen hast, indem du u
```suggestion
Bevor du zu den anderen Channels Zugriff bekommst, musst du dich in #🗣introductions (mit wenigstens 40 Zeichen) vorstellen und zeigen, dass du den Verhaltenskodex weiter unten gelesen hast, indem du unter dieser Nachricht mit einem Emoji reagierst 👇.
```

2019-12-06 22:09 UTC, snordmann commented on README_GERMAN.md
> +**SENDE NICHT DIESELBE NACHRICHT IN MEHRERE CHANNELS.** Wie werden deine Nachricht sehen und antworten, wenn wir Zeit haben.
```suggestion
**SENDE NICHT DIESELBE NACHRICHT IN MEHRERE CHANNELS.** Wir werden deine Nachricht sehen und antworten, wenn wir Zeit haben.
```

2019-12-06 22:09 UTC, snordmann commented on README_GERMAN.md
> +Bevor du eine Nachricht absendest, nehme dir bitte 30 Sekunden Zeit, um zu entscheiden, in welchen Channel diese Nachricht kommt:
```suggestion
Bevor du eine Nachricht absendest, nimm dir bitte 30 Sekunden Zeit, um zu entscheiden, in welchen Channel diese Nachricht kommt:
```

2019-12-06 22:09 UTC, snordmann commented on README_GERMAN.md
> +* Teile Tutorials oder Artikel die du nützlich gefunden hast in #📖share_resources
```suggestion
* Teile Tutorials oder Artikel, die du nützlich gefunden hast, in #📖share_resources 
```

2019-12-06 22:09 UTC, sbibow commented on README_GERMAN.md
> +Code aus den Videos/Streams kann auf GitHub gefunden werden: <https://github.com/CodingGarden>
```suggestion
Der Quellcode aus den Videos/Streams kann auf GitHub gefunden werden: <https://github.com/CodingGarden>
```

2019-12-06 22:09 UTC, sbibow commented on README_GERMAN.md
> +Indem du diesen Server betrittst oder Nachrichten schreibst, stimmst du dabei zu, dem Verhaltenskodex folge zu leisten. Alle Verstöße gegen diesen Verhaltenskodex können Konsequenzen wie einen Kick o
```suggestion
Indem du diesen Server betrittst oder Nachrichten schreibst, stimmst du dabei zu, dem Verhaltenskodex folge zu leisten. Alle Verstöße gegen diesen Verhaltenskodex können Konsequenzen wie einen Kick oder temporären Ban nach Ermessen der Moderatoren (Pruners) haben. Sei nett!
```

2019-12-06 22:09 UTC, sbibow commented on README_GERMAN.md
> +Teilnehmer, die gegen Richtlinien verstoßen, und gebeten werden, aufzuhören, sollten es sofort tun. Falls ein Teilnehmer sich belästigend Verhaltet, könnte es in Konsequenzen wie einem Kick oder temp
```suggestion
Teilnehmer, die gegen Richtlinien verstoßen, und gebeten werden, aufzuhören, sollten es sofort tun. Falls ein Teilnehmer sich belästigend verhält, könnte es in Konsequenzen wie einem Kick oder temporären Ban nach Ermessen der Moderatoren erfolgen. Sei nett!
```

2019-12-06 22:28 UTC, spVierSechs commented
The errors are mostly due to my insert key being broken, so I'm accidentally overwriting characters sometimes.  I currently have no idea how to merge your suggested changes, but I'll add them ASAP when I'm on my desktop PC again.  
  
CJ, if you're approving this, add the requested changes afterwards please.  
  
Again, I apologize for the spelling/grammar mistakes.

2019-12-07 03:01 UTC, w3cj commented
No worries! Thanks so much to both of you for the contributions. I should be able to merge it all in.

2019-12-07 03:03 UTC, w3cj commented
@spVierSechs It looks like I can't merge the changes directly. I'll wait for you to merge them and then I'll merge the pull request. No rush! Just leave a comment here when you've merged all the suggestions.

2019-12-08 13:14 UTC, spVierSechs commented
Merged the suggestions.

2019-12-08 16:30 UTC, merged

2019-12-09 03:27 UTC, w3cj commented
Thanks for all your efforts!

I added a link in the README. Will you let me know if this is a good translation of:

>German: To read this message in german, click here.

>Deutsch: Um diese Nachricht auf Deutsch zu lesen, klicken Sie hier.

I used google translate.