Update spanish translation.
CodingGarden/discord-welcome-code-of-conduct pull request #4
Opened 2019-12-08 16:28 UTC by w3cj

2019-12-08 16:29 UTC, w3cj commented
@angelhdz I created a pull request for you. 😉 

@AndCotOli Can you look over Angel's updates?

2019-12-08 16:29 UTC, w3cj commented on README_SPANISH.md
> +¡Hola amigo(a)! Bienvenido(a) al servidor de Discord de Coding Garden.
Nice! I want this to be gender neutral if possible.

2019-12-08 16:29 UTC, AndCotOli commented
Sure

2019-12-08 17:19 UTC, AndCotOli requested changes
Just 3 little changes, good job @angelhdz !

2019-12-08 17:19 UTC, AndCotOli commented on README_SPANISH.md
> +¡Hola amigo(a)! Bienvenido(a) al servidor de Discord de Coding Garden.
Gender neutrality is better expressed with /a -> _amigo/a_

2019-12-08 17:19 UTC, AndCotOli commented on README_SPANISH.md
> +Para tener acceso al resto de los canales, debes presentarte en #🗣introductions (mínimo 40 caracteres) y aceptar el código de conducta reaccionando con un emoticono :point_down:.
Typo: _carácteres_

2019-12-08 17:19 UTC, AndCotOli commented on README_SPANISH.md
> +  * Comentarios ofensivos hacía la identidad y expresión de género, orientación sexual, raza, etnia, idioma, tamaño, neurotipo, habilidad, clase, religión, cultura, subcultura, opinión política, edad
_Neurotipo_ doen't exist in Spanish.

2019-12-08 17:20 UTC, AndCotOli commented
And thanks for fixing my typos!

2019-12-08 22:49 UTC, angelhdz commented
Good! Team effort!

About the neutotype thingy... you're right, but I think it doesn't exist yet because it's a concept that it's not very talked in Spanish cultures....

I was researching before adding that, and while the term neurotype doesn't exist in Spanish, there are topics about Neurotic conditions and Spectrum conditions. I didn't even knew about the neurotype term in English, I learned it from The Coding Train, and from the Netflix show Atypical.

So I guess, the term will eventually make it to the Spanish slang. But not currently. There isn't an equivalent I believe.

Eagerly to read your feedback. Happy Holidays!

2019-12-09 03:25 UTC, w3cj commented
@angelhdz If you push a commit to your fork / branch (or [edit on github](https://github.com/angelhdz/discord-welcome-code-of-conduct/tree/patch-1)) with the changes suggested, it will show up here.

Google translate for neurotype translates it to neurotipo: https://translate.google.com/#view=home&op=translate&sl=en&tl=es&text=neurotype

I actually really like the show Atypical! Do they have a spanish overdub?

2019-12-09 05:59 UTC, angelhdz commented
@w3cj it's on Netflix.  According to my Google search, Atypical has Spanish audio and subtitles.

2019-12-09 08:38 UTC, angelhdz commented on README_SPANISH.md
> +Para tener acceso al resto de los canales, debes presentarte en #🗣introductions (mínimo 40 caracteres) y aceptar el código de conducta reaccionando con un emoticono :point_down:.
http://lema.rae.es/dpd/srv/search?key=car%E1cter

2019-12-14 14:19 UTC, merged